### ISSUE TITLE
ATS support for iOS 9

### ISSUE THREAD

**Issue by alistra** [quantcast/ios-measurement#17]
In your code you're using @"http://m.quantcount.com/mobile" as the link to push analytics to.

Since iOS 9 all plain text http requests are blocked by default (http://www.neglectedpotential.com/2015/06/working-with-apples-application-transport-security/)

Please use https:// (TLS 1.2 with forward secrecy) on this API endpoint and enable people to use your library without adding an exception.

**Comment by SmithKevin** [comment]
Hi @alistra 
   The SDK comes with an option for secure connections.  You can find the documentation here: https://github.com/quantcast/ios-measurement#secure-data-uploads.   In a future release we be sure to change it to the default.   Let me know if that still doesn't work for you.

Thanks,
   Kevin

**Comment by alistra** [comment]
Is there an option to use the CocoaPod with the define flag? Or do I have to manually modify the podspec?

**Comment by SmithKevin** [comment]
There is a "secure-data" subspec that you can use.   This should add the Security dependency and also the needed #define

**Comment by thisisjeffwong** [comment]
Does Quantcast servers support TLS 1.2 already?

**Comment by SmithKevin** [comment]
Hi @thisisjeffwong ,
  Quantcast does support TLS 1.2, but not a 256 cipher quite yet.   We are in the process of obtaining and testing the certificate and expect our servers to be fully compliant by next Wednesday 9/23/15.  In the mean time you can add the following exception to your info.plist in order to keep the SDK running:
```xml
<dict>
	<key>NSExceptionDomains</key>
	<dict>
		<key>quantcount.com</key>
		<dict>
			<key>NSIncludesSubdomains</key>
			<true/>
			<key>NSExceptionRequiresForwardSecrecy</key>
			<false/>
		</dict>
	</dict>
</dict>
```

I apologize that we are a little behind on this and will keep this issue posted on our progress.

**Comment by thisisjeffwong** [comment]
Thanks! Having your servers ready by next Wednesday is pretty good; a lot sooner than a lot of other APIs we're using.

**Comment by SmithKevin** [comment]
Great news.   Our server guys are faster than expected.   We now should be fully compliant with Apples new ATS without the need for any exceptions.   Please let me know if you are still running into any issues.
