### ISSUE TITLE
Compilation warnings in Xcode 7

### ISSUE THREAD

**Issue by thisisjeffwong** [quantcast/ios-measurement#18]
Could you guys fix the warnings for `QuantcastOptOutViewController`? 

Thanks!

**Comment by SmithKevin** [comment]
This should be fixed in the latest 1.5.0 push.   Please let me know if that is not the case

**Comment by thisisjeffwong** [comment]
Cool! Thanks for the quick response. Could you push the new podspec to
Cocoapods? We'd prefer not to point to a commit.

**Comment by SmithKevin** [comment]
Oops I always forget.  Cocoapod now pushed.
