### ISSUE TITLE
Error when using Cocoapods with use_frameworks! setting

### ISSUE THREAD

**Issue by tumatauenga** [quantcast/ios-measurement#19]
I have incorporated the Quantcast SDK via Cocoapods with the `use_frameworks!` option set in my Podfile. 

When compiling the app I get the following errors:

1) Include of non-modular header inside framework module '`Quantcast_Measure.QuantcastDatabase`'

This error is shown at this line: https://github.com/quantcast/ios-measurement/blob/b3b50892ecb54b9abb88c7f02ac61e8d275ab5d9/Quantcast-iOS-Measurement/QuantcastDatabase.h#L15

2) Include of non-modular header inside framework module '`Quantcast_Measure.QuantcastNetworkReachability`'

This error is shown at this line: https://github.com/quantcast/ios-measurement/blob/b3b50892ecb54b9abb88c7f02ac61e8d275ab5d9/Quantcast-iOS-Measurement/QuantcastNetworkReachability.h#L15

I can get around this by setting `Allow Non-modular Includes In Framework Modules` to `Yes` in the Build Settings of my project, but I would rather not change that setting if possible.

**Comment by SmithKevin** [comment]
Thanks for letting us know.   Looks like I figured out how to fix it.    I will push an update in the next few days.

**Comment by tumatauenga** [comment]
Thanks - if you could let me know when it's pushed that would be fantastic.

**Comment by SmithKevin** [comment]
@tumatauenga    Sorry for the delay.   This issues should now be fixed.   Please let me know if that is not the case.
