### ISSUE TITLE
Analyzer warning in code

### ISSUE THREAD

**Issue by alistra** [quantcast/ios-measurement#20]
<img width="1128" alt="screen shot 2015-11-03 at 13 15 53" src="https://cloud.githubusercontent.com/assets/233144/10907735/0cabf174-822d-11e5-9c3c-9ed2b6b3c51d.png">

**Comment by SmithKevin** [comment]
Thanks for bringing this up.   In this particular case, no call to this method ever sends a NULL error variable, so I would not expect any issues.    In the next release, I will wrap both these in NULL checks in order to prevent the warning.
