### ISSUE TITLE
Reachability needs to be updated for IPv6 support

### ISSUE THREAD

**Issue by JoeSzymanski** [quantcast/ios-measurement#21]
Soon, Apple is going to start rejecting apps that don't provide IPv6 support. Part of the documentation indicates that usage of SCNetworkReachability with the 0.0.0.0 IPv4 address is a common area that will break the IPv6 support.

See https://developer.apple.com/library/ios/documentation/NetworkingInternetWeb/Conceptual/NetworkingOverview/UnderstandingandPreparingfortheIPv6Transition/UnderstandingandPreparingfortheIPv6Transition.html for some additional information on this.

The reachability code in the Quantcast library should be updated to perform reachability checks based on a host name instead of an IP address, per the Apple documentation.

**Comment by SmithKevin** [comment]
@JoeSzymanski  Thanks for bringing this to our attention.  I will be looking into this this week and should have a fix in our next release.

**Comment by JoeSzymanski** [comment]
@SmithKevin Apple has released information indicating that IPv6 support will now be a requirement starting on June 1, 2016 (See https://developer.apple.com/news/?id=05042016a). That makes this request a much higher priority.

Are there any updates regarding this issue?

**Comment by SmithKevin** [comment]
Hi @JoeSzymanski.  
   Sorry about that.  The code has been changed, but a release was never scheduled.  I will make sure a new version is released this week.   Thanks for the heads up.

**Comment by kidneyband** [comment]
@SmithKevin when will the IPv6 support update come? I'm keeping an eye on that.

**Comment by SmithKevin** [comment]
Hey all,
   Sorry for the delay.  I have pushed the update which removes the ip address specific code from reachability.  This should make it safe for both ipv6 and ipv4.  Let me know if you have any other issues.   Thanks again for bringing it to out attention.
