### ISSUE TITLE
Documentation doesn't indicate need for Security.framework

### ISSUE THREAD

**Issue by michaelkamprath** [quantcast/ios-measurement#22]
The `README.md` files does not list the need to link to `Security.framework` under the [Set Up Your Xcode](https://github.com/quantcast/ios-measurement#set-up-your-xcode-project) Project section. However, with the latest update, my project will not build without it, likely due to what is explained in the [Secure Data Uploads](https://github.com/quantcast/ios-measurement#secure-data-uploads) section.

**Comment by SmithKevin** [comment]
Thank you @michaelkamprath 
Looks like that was overlooked.   I will update that this week.
