### ISSUE TITLE
Deprecated methods in iOS 9

### ISSUE THREAD

**Issue by michaelkamprath** [quantcast/ios-measurement#23]
The `QuantcastUtils.m` uses methods deprecated in iOS 9.0 at lines [524](https://github.com/quantcast/ios-measurement/blob/master/Quantcast-iOS-Measurement/QuantcastUtils.m#L524) and [641](https://github.com/quantcast/ios-measurement/blob/master/Quantcast-iOS-Measurement/QuantcastUtils.m#L641).

**Comment by SmithKevin** [comment]
@michaelkamprath 
  Sorry for the delay here.   I have removed one of the deprecated methods (URL Escaping).  The other one concerning NSURLConnection is not going to be as easy as I hoped, so I have pushed it to the next release.   Changing the SDK to use NSURLSession is a much larger change to the network layer that I want to be sure I do it right and take full advantage of its new features.  Thanks again for your continued support.
