### ISSUE TITLE
IPv6 changes

### ISSUE THREAD

**Issue by thisisjeffwong** [quantcast/ios-measurement#24]
Hi,
Could you guys push a new release with the IPv6 changes commit to Cocoapods? It would really helpful.

Thanks!

**Comment by SmithKevin** [comment]
Will do.  I totally forgot about that.  I'll let you know when it is up.

**Comment by SmithKevin** [comment]
Hi @thisisjeffwong 
   Version 1.5.3 should now be available on Cocoapods.   Let me know if you have any other issues.

**Comment by thisisjeffwong** [comment]
thanks for pushing it out so quickly!
