### ISSUE TITLE
Troubles  on Xcode 8 with Swift 3 

### ISSUE THREAD

**Issue by ro6lyo** [quantcast/ios-measurement#25]
![screenshot 2016-11-02 14 47 38](https://cloud.githubusercontent.com/assets/13335070/19929384/bf92c666-a10b-11e6-87ab-87e5b2c23b10.png)

Compiler  warns to replace the names of notification observers... So I had to manually add `#import <UIKit/UIKit.h>` on top of the file  in order to recognize them
And there is also deprecated functions on
 1. `"QuantcastMeasurement+InstallAttribution.m"` line 47
2. `"QuantcastUtils.m"` line 639

**Comment by SmithKevin** [comment]
@ro6lyo Thanks for bringing this to our attention.   Glad you ended up fixing it in your project.  We will address these issue in the next release.

**Comment by GChearswat** [comment]
Same issues and fixes here. I opened a pull request on these. Please review + merge!
